# Change these first
owner: avanpost200 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.avanpost20.ru
  - name: CDN
    url: https://autumn.avanpost20.ru?t=2
  - name: Voice
    url: https://vortex.avanpost20.ru
  - name: Proxy Service
    url: https://january.avanpost20.ru
  - name: Client
    url: https://app.avanpost20.ru
  - name: Static Resources
    url: https://static.avanpost20.ru
    expectedStatusCodes:
      - 200
      - 404
  - name: Mail
    check: "tcp-ping"
    url: $MAIL_SERVER
    port: 25

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.avanpost20.ru
  # baseUrl: /your-repo-name
  logoUrl: /logo.png
  favicon: /logo.png
  faviconSvg: /logo.svg
  name: "Next Status"
  introTitle: "Next Service Status"
  introMessage: "Next is a user-first chat platform built with modern web technologies."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://next.avanpost20.ru

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
